const arr_0 = [ "Containers",
    [ "Live_learn",
        [ "Common_this", [ "_src" ] ],
        [ "Docs_this", [ "_src" ] ],
        [ "www_this", [ "_src" ] ],
        [ "_src" ] ],
    [ "Point_learn",
        [ "the_part_of_this",
            [ "Common_this", [ "_src" ] ],
            [ "Docs_this", [ "_src" ] ],
            [ "www_this", [ "_src" ] ],
            [ "_src" ] ] ],
    [ "_src" ],
    [ "Intro_to_this",
        [ "Common_this", [ "_src" ] ],
        [ "Docs_this", [ "_src" ] ],
        [ "www_this", [ "_src" ] ],
        [ "_src" ] ],
    [ "Use_this",
        [ "First_steps", [ "_src" ] ],
        [ "Hints", [ "_src" ] ] ],
    [ "Workout_this", [ "_src" ] ],
    [ "_src" ] ];

